#!/usr/bin/env php
<?php
// REQUIRED! Constant contents absolute path to run script
define('PATH', dirname(__FILE__));

// path for configs file
$configPath = dirname(__FILE__) . DIRECTORY_SEPARATOR . '../../..' . DIRECTORY_SEPARATOR . 'application' .
    DIRECTORY_SEPARATOR . 'configs';
define('CONFIG_PATH', $configPath);

$params = array();
if ($argc > 2) {
    for ($i = 2; $i <= $argc - 1; $i++) $params[] = $argv[$i];
}

require_once 'vendor/autoload.php';

MTool_Exec::run($argv[1], $params);